FROM dorowu/ubuntu-desktop-lxde-vnc:latest
EXPOSE 6080:80
RUN sudo apt update
RUN sudo apt-get install -y git 
RUN sudo apt install -y nodejs npm 
RUN curl -sL https://deb.nodesource.com/setup_16.x | sudo bash - #change nodejs version to 16.15.0
RUN sudo apt install -y nodejs
RUN npm install --global yarn
RUN npm install -g node-gyp
RUN sudo apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev python-is-python3
RUN sudo apt-get install -y pkg-config
RUN sudo apt-get install -y fakeroot rpm
RUN git clone https://github.com/Microsoft/vscode.git
WORKDIR /root/vscode
RUN yarn
WORKDIR /root/vscode/scripts/
CMD ./code.sh --no-sandbox
