---
- hosts: localhost
  become: yes
  vars:
    datanum: "{{ unidata.json.result.records| count }}"
    
  tasks:
    - name: Query IT university graduate data
      uri:
        url: https://data.gov.sg/api/action/datastore_search?resource_id=115bf8a7-46df-466c-b7fc-375ef3c1b425&q=information+technology
        return_content: yes
        method: GET
      register: unidata
    - debug:
        msg: "Course: {{ unidata.json.result.records[item]['course'] }} Year: {{ unidata.json.result.records[item]['year'] }} Sex: {{ unidata.json.result.records[item]['sex'] }} Graduates: {{ unidata.json.result.records[item]['graduates'] }}"
      loop: "{{ range(0, datanum|int,2) |list }}" # note: ranges for only sex:MF

    - name: Output content for uni graduates to file
      shell: echo "Course:{{ unidata.json.result.records[item]['course'] }} Year:{{ unidata.json.result.records[item]['year'] }} Sex:{{ unidata.json.result.records[item]['sex'] }} Graduates:{{ unidata.json.result.records[item]['graduates'] }}" >> it_uni_data.csv
      loop: "{{ range(0,datanum|int,2) |list }}"

    - name: Calculate total number of IT university graduates and print to file
      set_fact:
        totaluni: "{{ totaluni|default(0)|int + unidata.json.result.records[item]['graduates']|int }}"
      loop: "{{ range(0,datanum|int,2)|list }}"
    - shell: echo "Total University Graduates:{{ totaluni }}" >> it_uni_data.csv
    - debug:
        msg: "Total University Graduates: {{ totaluni }}"

    - name: Query IT polytechnic graduate data
      uri:
        url: https://data.gov.sg/api/action/datastore_search?resource_id=f358cf0d-61fa-4eeb-93a2-1eca971cf1a4&q=information+technology
        return_content: yes
        method: GET
      register: polydata
    - debug:
        msg: "Course: {{ polydata.json.result.records[item]['course'] }} Year: {{ polydata.json.result.records[item]['year'] }} Sex: {{ polydata.json.result.records[item]['sex'] }} Graduates: {{ polydata.json.result.records[item]['graduates'] }}"
      loop: "{{ range(0,datanum|int,2) |list }}" # note: ranges for only sex:MF

    - name: Output content for poly graduates to file
      shell: echo "Course:{{ polydata.json.result.records[item]['course'] }} Year:{{ polydata.json.result.records[item]['year'] }} Sex:{{ polydata.json.result.records[item]['sex'] }} Graduates:{{ polydata.json.result.records[item]['graduates'] }}" >> it_poly_data.csv
      loop: "{{ range(0,datanum|int,2) |list }}"

    - name: Calculate total number of IT poly graduates and print to file
      set_fact:
        totalpoly: "{{ totalpoly|default(0)|int + polydata.json.result.records[item]['graduates']|int }}"
      loop: "{{ range(0,datanum|int,2)|list }}"
    - shell: echo "Total Polytechnic Graduates:{{ totalpoly }}" >> it_poly_data.csv
    - debug:
        msg: "Total Polytechnic Graduates: {{ totalpoly }}"

    - name: Calculate the total number of IT graduates from University and Polytechnic
      set_fact:
        total: "{{ totaluni|int + totalpoly|int }}"
    - debug:
        msg: "Total Number of IT Graduates:{{ total }}"
    - shell: echo "Total Number of IT Graduates:{{ total }}" >> finaldata.txt
    